name: Server Release

# Controls when the workflow will run
on:
  # Only for a tag starting with a `v`
  push:
    tags:
      - "v*.*.*"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
        
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v2.7.0
        with:
          # GoReleaser version
          version: latest
          args: release -f .goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
